"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var isAuth_1 = require("../middleware/isAuth");
var isSuper_1 = require("../middleware/isSuper");
var AnnouncementController = require("../controllers/AnnouncementController");
var multer_1 = require("multer");
var upload_1 = require("../config/upload");
var upload = (0, multer_1.default)(upload_1.default);
var routes = express_1.default.Router();
routes.get("/announcements/list", isAuth_1.default, AnnouncementController.findList);
routes.get("/announcements", isAuth_1.default, AnnouncementController.index);
routes.get("/announcements/:id", isAuth_1.default, AnnouncementController.show);
routes.post("/announcements", isAuth_1.default, isSuper_1.default, AnnouncementController.store);
routes.put("/announcements/:id", isAuth_1.default, isSuper_1.default, AnnouncementController.update);
routes.delete("/announcements/:id", isAuth_1.default, isSuper_1.default, AnnouncementController.remove);
routes.post("/announcements/:id/media-upload", isAuth_1.default, isSuper_1.default, upload.array("file"), AnnouncementController.mediaUpload);
routes.delete("/announcements/:id/media-upload", isAuth_1.default, isSuper_1.default, AnnouncementController.deleteMedia);
exports.default = routes;
