"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var isAuth_1 = require("../middleware/isAuth");
var CampaignController = require("../controllers/CampaignController");
var multer_1 = require("multer");
var upload_1 = require("../config/upload");
var upload = (0, multer_1.default)(upload_1.default);
var routes = express_1.default.Router();
routes.get("/campaigns/list", isAuth_1.default, CampaignController.findList);
routes.get("/campaigns", isAuth_1.default, CampaignController.index);
routes.get("/campaigns/:id", isAuth_1.default, CampaignController.show);
routes.post("/campaigns", isAuth_1.default, CampaignController.store);
routes.put("/campaigns/:id", isAuth_1.default, CampaignController.update);
routes.delete("/campaigns/:id", isAuth_1.default, CampaignController.remove);
routes.post("/campaigns/:id/cancel", isAuth_1.default, CampaignController.cancel);
routes.post("/campaigns/:id/restart", isAuth_1.default, CampaignController.restart);
routes.post("/campaigns/:id/media-upload", isAuth_1.default, upload.array("file"), CampaignController.mediaUpload);
routes.delete("/campaigns/:id/media-upload", isAuth_1.default, CampaignController.deleteMedia);
exports.default = routes;
