"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var userRoutes_1 = require("./userRoutes");
var authRoutes_1 = require("./authRoutes");
var settingRoutes_1 = require("./settingRoutes");
var contactRoutes_1 = require("./contactRoutes");
var ticketRoutes_1 = require("./ticketRoutes");
var whatsappRoutes_1 = require("./whatsappRoutes");
var messageRoutes_1 = require("./messageRoutes");
var whatsappSessionRoutes_1 = require("./whatsappSessionRoutes");
var queueRoutes_1 = require("./queueRoutes");
var companyRoutes_1 = require("./companyRoutes");
var planRoutes_1 = require("./planRoutes");
var ticketNoteRoutes_1 = require("./ticketNoteRoutes");
var quickMessageRoutes_1 = require("./quickMessageRoutes");
var helpRoutes_1 = require("./helpRoutes");
var dashboardRoutes_1 = require("./dashboardRoutes");
var queueOptionRoutes_1 = require("./queueOptionRoutes");
var scheduleRoutes_1 = require("./scheduleRoutes");
var tagRoutes_1 = require("./tagRoutes");
var contactListRoutes_1 = require("./contactListRoutes");
var contactListItemRoutes_1 = require("./contactListItemRoutes");
var campaignRoutes_1 = require("./campaignRoutes");
var campaignSettingRoutes_1 = require("./campaignSettingRoutes");
var announcementRoutes_1 = require("./announcementRoutes");
var chatRoutes_1 = require("./chatRoutes");
var invoicesRoutes_1 = require("./invoicesRoutes");
var subScriptionRoutes_1 = require("./subScriptionRoutes");
var ticketTagRoutes_1 = require("./ticketTagRoutes");
var filesRoutes_1 = require("./filesRoutes");
var promptRouter_1 = require("./promptRouter");
var queueIntegrationRoutes_1 = require("./queueIntegrationRoutes");
var forgotPasswordRoutes_1 = require("./forgotPasswordRoutes");
var versionRoutes_1 = require("./versionRoutes");
var routes = (0, express_1.Router)();
routes.use(userRoutes_1.default);
routes.use("/auth", authRoutes_1.default);
routes.use(settingRoutes_1.default);
routes.use(contactRoutes_1.default);
routes.use(ticketRoutes_1.default);
routes.use(whatsappRoutes_1.default);
routes.use(messageRoutes_1.default);
routes.use(messageRoutes_1.default);
routes.use(whatsappSessionRoutes_1.default);
routes.use(queueRoutes_1.default);
routes.use(companyRoutes_1.default);
routes.use(planRoutes_1.default);
routes.use(ticketNoteRoutes_1.default);
routes.use(quickMessageRoutes_1.default);
routes.use(helpRoutes_1.default);
routes.use(dashboardRoutes_1.default);
routes.use(queueOptionRoutes_1.default);
routes.use(scheduleRoutes_1.default);
routes.use(tagRoutes_1.default);
routes.use(contactListRoutes_1.default);
routes.use(contactListItemRoutes_1.default);
routes.use(campaignRoutes_1.default);
routes.use(campaignSettingRoutes_1.default);
routes.use(announcementRoutes_1.default);
routes.use(chatRoutes_1.default);
routes.use(subScriptionRoutes_1.default);
routes.use(invoicesRoutes_1.default);
routes.use(ticketTagRoutes_1.default);
routes.use(filesRoutes_1.default);
routes.use(promptRouter_1.default);
routes.use(queueIntegrationRoutes_1.default);
routes.use(forgotPasswordRoutes_1.default);
routes.use(versionRoutes_1.default);
exports.default = routes;
