"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var isAuth_1 = require("../middleware/isAuth");
var ScheduleController = require("../controllers/ScheduleController");
var multer_1 = require("multer");
var upload_1 = require("../config/upload");
var upload = (0, multer_1.default)(upload_1.default);
var scheduleRoutes = express_1.default.Router();
scheduleRoutes.get("/schedules", isAuth_1.default, ScheduleController.index);
scheduleRoutes.post("/schedules", isAuth_1.default, ScheduleController.store);
scheduleRoutes.put("/schedules/:scheduleId", isAuth_1.default, ScheduleController.update);
scheduleRoutes.get("/schedules/:scheduleId", isAuth_1.default, ScheduleController.show);
scheduleRoutes.delete("/schedules/:scheduleId", isAuth_1.default, ScheduleController.remove);
scheduleRoutes.post("/schedules/:id/media-upload", isAuth_1.default, upload.array("file"), ScheduleController.mediaUpload);
scheduleRoutes.delete("/schedules/:id/media-upload", isAuth_1.default, ScheduleController.deleteMedia);
exports.default = scheduleRoutes;
