"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
var sequelize_typescript_1 = require("sequelize-typescript");
var uuid_1 = require("uuid");
var Contact_1 = require("./Contact");
var Message_1 = require("./Message");
var Queue_1 = require("./Queue");
var User_1 = require("./User");
var Whatsapp_1 = require("./Whatsapp");
var Company_1 = require("./Company");
var QueueOption_1 = require("./QueueOption");
var Tag_1 = require("./Tag");
var TicketTag_1 = require("./TicketTag");
var QueueIntegrations_1 = require("./QueueIntegrations");
var Prompt_1 = require("./Prompt");
var Ticket = function () {
    var _classDecorators = [sequelize_typescript_1.Table];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _classSuper = sequelize_typescript_1.Model;
    var _staticExtraInitializers = [];
    var _static_setUUID_decorators;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _unreadMessages_decorators;
    var _unreadMessages_initializers = [];
    var _unreadMessages_extraInitializers = [];
    var _lastMessage_decorators;
    var _lastMessage_initializers = [];
    var _lastMessage_extraInitializers = [];
    var _isGroup_decorators;
    var _isGroup_initializers = [];
    var _isGroup_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var _userId_decorators;
    var _userId_initializers = [];
    var _userId_extraInitializers = [];
    var _user_decorators;
    var _user_initializers = [];
    var _user_extraInitializers = [];
    var _contactId_decorators;
    var _contactId_initializers = [];
    var _contactId_extraInitializers = [];
    var _contact_decorators;
    var _contact_initializers = [];
    var _contact_extraInitializers = [];
    var _whatsappId_decorators;
    var _whatsappId_initializers = [];
    var _whatsappId_extraInitializers = [];
    var _whatsapp_decorators;
    var _whatsapp_initializers = [];
    var _whatsapp_extraInitializers = [];
    var _queueId_decorators;
    var _queueId_initializers = [];
    var _queueId_extraInitializers = [];
    var _queue_decorators;
    var _queue_initializers = [];
    var _queue_extraInitializers = [];
    var _chatbot_decorators;
    var _chatbot_initializers = [];
    var _chatbot_extraInitializers = [];
    var _queueOptionId_decorators;
    var _queueOptionId_initializers = [];
    var _queueOptionId_extraInitializers = [];
    var _queueOption_decorators;
    var _queueOption_initializers = [];
    var _queueOption_extraInitializers = [];
    var _messages_decorators;
    var _messages_initializers = [];
    var _messages_extraInitializers = [];
    var _ticketTags_decorators;
    var _ticketTags_initializers = [];
    var _ticketTags_extraInitializers = [];
    var _tags_decorators;
    var _tags_initializers = [];
    var _tags_extraInitializers = [];
    var _companyId_decorators;
    var _companyId_initializers = [];
    var _companyId_extraInitializers = [];
    var _company_decorators;
    var _company_initializers = [];
    var _company_extraInitializers = [];
    var _uuid_decorators;
    var _uuid_initializers = [];
    var _uuid_extraInitializers = [];
    var _useIntegration_decorators;
    var _useIntegration_initializers = [];
    var _useIntegration_extraInitializers = [];
    var _integrationId_decorators;
    var _integrationId_initializers = [];
    var _integrationId_extraInitializers = [];
    var _queueIntegration_decorators;
    var _queueIntegration_initializers = [];
    var _queueIntegration_extraInitializers = [];
    var _typebotSessionId_decorators;
    var _typebotSessionId_initializers = [];
    var _typebotSessionId_extraInitializers = [];
    var _typebotStatus_decorators;
    var _typebotStatus_initializers = [];
    var _typebotStatus_extraInitializers = [];
    var _promptId_decorators;
    var _promptId_initializers = [];
    var _promptId_extraInitializers = [];
    var _prompt_decorators;
    var _prompt_initializers = [];
    var _prompt_extraInitializers = [];
    var _fromMe_decorators;
    var _fromMe_initializers = [];
    var _fromMe_extraInitializers = [];
    var _amountUsedBotQueues_decorators;
    var _amountUsedBotQueues_initializers = [];
    var _amountUsedBotQueues_extraInitializers = [];
    var Ticket = _classThis = /** @class */ (function (_super) {
        __extends(Ticket_1, _super);
        function Ticket_1() {
            var _this = _super !== null && _super.apply(this, arguments) || this;
            _this.id = __runInitializers(_this, _id_initializers, void 0);
            _this.status = (__runInitializers(_this, _id_extraInitializers), __runInitializers(_this, _status_initializers, void 0));
            _this.unreadMessages = (__runInitializers(_this, _status_extraInitializers), __runInitializers(_this, _unreadMessages_initializers, void 0));
            _this.lastMessage = (__runInitializers(_this, _unreadMessages_extraInitializers), __runInitializers(_this, _lastMessage_initializers, void 0));
            _this.isGroup = (__runInitializers(_this, _lastMessage_extraInitializers), __runInitializers(_this, _isGroup_initializers, void 0));
            _this.createdAt = (__runInitializers(_this, _isGroup_extraInitializers), __runInitializers(_this, _createdAt_initializers, void 0));
            _this.updatedAt = (__runInitializers(_this, _createdAt_extraInitializers), __runInitializers(_this, _updatedAt_initializers, void 0));
            _this.userId = (__runInitializers(_this, _updatedAt_extraInitializers), __runInitializers(_this, _userId_initializers, void 0));
            _this.user = (__runInitializers(_this, _userId_extraInitializers), __runInitializers(_this, _user_initializers, void 0));
            _this.contactId = (__runInitializers(_this, _user_extraInitializers), __runInitializers(_this, _contactId_initializers, void 0));
            _this.contact = (__runInitializers(_this, _contactId_extraInitializers), __runInitializers(_this, _contact_initializers, void 0));
            _this.whatsappId = (__runInitializers(_this, _contact_extraInitializers), __runInitializers(_this, _whatsappId_initializers, void 0));
            _this.whatsapp = (__runInitializers(_this, _whatsappId_extraInitializers), __runInitializers(_this, _whatsapp_initializers, void 0));
            _this.queueId = (__runInitializers(_this, _whatsapp_extraInitializers), __runInitializers(_this, _queueId_initializers, void 0));
            _this.queue = (__runInitializers(_this, _queueId_extraInitializers), __runInitializers(_this, _queue_initializers, void 0));
            _this.chatbot = (__runInitializers(_this, _queue_extraInitializers), __runInitializers(_this, _chatbot_initializers, void 0));
            _this.queueOptionId = (__runInitializers(_this, _chatbot_extraInitializers), __runInitializers(_this, _queueOptionId_initializers, void 0));
            _this.queueOption = (__runInitializers(_this, _queueOptionId_extraInitializers), __runInitializers(_this, _queueOption_initializers, void 0));
            _this.messages = (__runInitializers(_this, _queueOption_extraInitializers), __runInitializers(_this, _messages_initializers, void 0));
            _this.ticketTags = (__runInitializers(_this, _messages_extraInitializers), __runInitializers(_this, _ticketTags_initializers, void 0));
            _this.tags = (__runInitializers(_this, _ticketTags_extraInitializers), __runInitializers(_this, _tags_initializers, void 0));
            _this.companyId = (__runInitializers(_this, _tags_extraInitializers), __runInitializers(_this, _companyId_initializers, void 0));
            _this.company = (__runInitializers(_this, _companyId_extraInitializers), __runInitializers(_this, _company_initializers, void 0));
            _this.uuid = (__runInitializers(_this, _company_extraInitializers), __runInitializers(_this, _uuid_initializers, void 0));
            _this.useIntegration = (__runInitializers(_this, _uuid_extraInitializers), __runInitializers(_this, _useIntegration_initializers, void 0));
            _this.integrationId = (__runInitializers(_this, _useIntegration_extraInitializers), __runInitializers(_this, _integrationId_initializers, void 0));
            _this.queueIntegration = (__runInitializers(_this, _integrationId_extraInitializers), __runInitializers(_this, _queueIntegration_initializers, void 0));
            _this.typebotSessionId = (__runInitializers(_this, _queueIntegration_extraInitializers), __runInitializers(_this, _typebotSessionId_initializers, void 0));
            _this.typebotStatus = (__runInitializers(_this, _typebotSessionId_extraInitializers), __runInitializers(_this, _typebotStatus_initializers, void 0));
            _this.promptId = (__runInitializers(_this, _typebotStatus_extraInitializers), __runInitializers(_this, _promptId_initializers, void 0));
            _this.prompt = (__runInitializers(_this, _promptId_extraInitializers), __runInitializers(_this, _prompt_initializers, void 0));
            _this.fromMe = (__runInitializers(_this, _prompt_extraInitializers), __runInitializers(_this, _fromMe_initializers, void 0));
            _this.amountUsedBotQueues = (__runInitializers(_this, _fromMe_extraInitializers), __runInitializers(_this, _amountUsedBotQueues_initializers, void 0));
            __runInitializers(_this, _amountUsedBotQueues_extraInitializers);
            return _this;
        }
        Ticket_1.setUUID = function (ticket) {
            ticket.uuid = (0, uuid_1.v4)();
        };
        return Ticket_1;
    }(_classSuper));
    __setFunctionName(_classThis, "Ticket");
    (function () {
        var _a;
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create((_a = _classSuper[Symbol.metadata]) !== null && _a !== void 0 ? _a : null) : void 0;
        _id_decorators = [sequelize_typescript_1.PrimaryKey, sequelize_typescript_1.AutoIncrement, sequelize_typescript_1.Column];
        _status_decorators = [(0, sequelize_typescript_1.Column)({ defaultValue: "pending" })];
        _unreadMessages_decorators = [sequelize_typescript_1.Column];
        _lastMessage_decorators = [sequelize_typescript_1.Column];
        _isGroup_decorators = [(0, sequelize_typescript_1.Default)(false), sequelize_typescript_1.Column];
        _createdAt_decorators = [sequelize_typescript_1.CreatedAt];
        _updatedAt_decorators = [sequelize_typescript_1.UpdatedAt];
        _userId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return User_1.default; }), sequelize_typescript_1.Column];
        _user_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return User_1.default; })];
        _contactId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return Contact_1.default; }), sequelize_typescript_1.Column];
        _contact_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return Contact_1.default; })];
        _whatsappId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return Whatsapp_1.default; }), sequelize_typescript_1.Column];
        _whatsapp_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return Whatsapp_1.default; })];
        _queueId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return Queue_1.default; }), sequelize_typescript_1.Column];
        _queue_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return Queue_1.default; })];
        _chatbot_decorators = [sequelize_typescript_1.Column];
        _queueOptionId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return QueueOption_1.default; }), sequelize_typescript_1.Column];
        _queueOption_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return QueueOption_1.default; })];
        _messages_decorators = [(0, sequelize_typescript_1.HasMany)(function () { return Message_1.default; })];
        _ticketTags_decorators = [(0, sequelize_typescript_1.HasMany)(function () { return TicketTag_1.default; })];
        _tags_decorators = [(0, sequelize_typescript_1.BelongsToMany)(function () { return Tag_1.default; }, function () { return TicketTag_1.default; })];
        _companyId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return Company_1.default; }), sequelize_typescript_1.Column];
        _company_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return Company_1.default; })];
        _uuid_decorators = [(0, sequelize_typescript_1.Default)((0, uuid_1.v4)()), sequelize_typescript_1.Column];
        _static_setUUID_decorators = [sequelize_typescript_1.BeforeCreate];
        _useIntegration_decorators = [(0, sequelize_typescript_1.Default)(false), sequelize_typescript_1.Column];
        _integrationId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return QueueIntegrations_1.default; }), sequelize_typescript_1.Column];
        _queueIntegration_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return QueueIntegrations_1.default; })];
        _typebotSessionId_decorators = [sequelize_typescript_1.Column];
        _typebotStatus_decorators = [(0, sequelize_typescript_1.Default)(false), sequelize_typescript_1.Column];
        _promptId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return Prompt_1.default; }), sequelize_typescript_1.Column];
        _prompt_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return Prompt_1.default; })];
        _fromMe_decorators = [sequelize_typescript_1.Column];
        _amountUsedBotQueues_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Default)(0), sequelize_typescript_1.Column];
        __esDecorate(_classThis, null, _static_setUUID_decorators, { kind: "method", name: "setUUID", static: true, private: false, access: { has: function (obj) { return "setUUID" in obj; }, get: function (obj) { return obj.setUUID; } }, metadata: _metadata }, null, _staticExtraInitializers);
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _unreadMessages_decorators, { kind: "field", name: "unreadMessages", static: false, private: false, access: { has: function (obj) { return "unreadMessages" in obj; }, get: function (obj) { return obj.unreadMessages; }, set: function (obj, value) { obj.unreadMessages = value; } }, metadata: _metadata }, _unreadMessages_initializers, _unreadMessages_extraInitializers);
        __esDecorate(null, null, _lastMessage_decorators, { kind: "field", name: "lastMessage", static: false, private: false, access: { has: function (obj) { return "lastMessage" in obj; }, get: function (obj) { return obj.lastMessage; }, set: function (obj, value) { obj.lastMessage = value; } }, metadata: _metadata }, _lastMessage_initializers, _lastMessage_extraInitializers);
        __esDecorate(null, null, _isGroup_decorators, { kind: "field", name: "isGroup", static: false, private: false, access: { has: function (obj) { return "isGroup" in obj; }, get: function (obj) { return obj.isGroup; }, set: function (obj, value) { obj.isGroup = value; } }, metadata: _metadata }, _isGroup_initializers, _isGroup_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, null, _userId_decorators, { kind: "field", name: "userId", static: false, private: false, access: { has: function (obj) { return "userId" in obj; }, get: function (obj) { return obj.userId; }, set: function (obj, value) { obj.userId = value; } }, metadata: _metadata }, _userId_initializers, _userId_extraInitializers);
        __esDecorate(null, null, _user_decorators, { kind: "field", name: "user", static: false, private: false, access: { has: function (obj) { return "user" in obj; }, get: function (obj) { return obj.user; }, set: function (obj, value) { obj.user = value; } }, metadata: _metadata }, _user_initializers, _user_extraInitializers);
        __esDecorate(null, null, _contactId_decorators, { kind: "field", name: "contactId", static: false, private: false, access: { has: function (obj) { return "contactId" in obj; }, get: function (obj) { return obj.contactId; }, set: function (obj, value) { obj.contactId = value; } }, metadata: _metadata }, _contactId_initializers, _contactId_extraInitializers);
        __esDecorate(null, null, _contact_decorators, { kind: "field", name: "contact", static: false, private: false, access: { has: function (obj) { return "contact" in obj; }, get: function (obj) { return obj.contact; }, set: function (obj, value) { obj.contact = value; } }, metadata: _metadata }, _contact_initializers, _contact_extraInitializers);
        __esDecorate(null, null, _whatsappId_decorators, { kind: "field", name: "whatsappId", static: false, private: false, access: { has: function (obj) { return "whatsappId" in obj; }, get: function (obj) { return obj.whatsappId; }, set: function (obj, value) { obj.whatsappId = value; } }, metadata: _metadata }, _whatsappId_initializers, _whatsappId_extraInitializers);
        __esDecorate(null, null, _whatsapp_decorators, { kind: "field", name: "whatsapp", static: false, private: false, access: { has: function (obj) { return "whatsapp" in obj; }, get: function (obj) { return obj.whatsapp; }, set: function (obj, value) { obj.whatsapp = value; } }, metadata: _metadata }, _whatsapp_initializers, _whatsapp_extraInitializers);
        __esDecorate(null, null, _queueId_decorators, { kind: "field", name: "queueId", static: false, private: false, access: { has: function (obj) { return "queueId" in obj; }, get: function (obj) { return obj.queueId; }, set: function (obj, value) { obj.queueId = value; } }, metadata: _metadata }, _queueId_initializers, _queueId_extraInitializers);
        __esDecorate(null, null, _queue_decorators, { kind: "field", name: "queue", static: false, private: false, access: { has: function (obj) { return "queue" in obj; }, get: function (obj) { return obj.queue; }, set: function (obj, value) { obj.queue = value; } }, metadata: _metadata }, _queue_initializers, _queue_extraInitializers);
        __esDecorate(null, null, _chatbot_decorators, { kind: "field", name: "chatbot", static: false, private: false, access: { has: function (obj) { return "chatbot" in obj; }, get: function (obj) { return obj.chatbot; }, set: function (obj, value) { obj.chatbot = value; } }, metadata: _metadata }, _chatbot_initializers, _chatbot_extraInitializers);
        __esDecorate(null, null, _queueOptionId_decorators, { kind: "field", name: "queueOptionId", static: false, private: false, access: { has: function (obj) { return "queueOptionId" in obj; }, get: function (obj) { return obj.queueOptionId; }, set: function (obj, value) { obj.queueOptionId = value; } }, metadata: _metadata }, _queueOptionId_initializers, _queueOptionId_extraInitializers);
        __esDecorate(null, null, _queueOption_decorators, { kind: "field", name: "queueOption", static: false, private: false, access: { has: function (obj) { return "queueOption" in obj; }, get: function (obj) { return obj.queueOption; }, set: function (obj, value) { obj.queueOption = value; } }, metadata: _metadata }, _queueOption_initializers, _queueOption_extraInitializers);
        __esDecorate(null, null, _messages_decorators, { kind: "field", name: "messages", static: false, private: false, access: { has: function (obj) { return "messages" in obj; }, get: function (obj) { return obj.messages; }, set: function (obj, value) { obj.messages = value; } }, metadata: _metadata }, _messages_initializers, _messages_extraInitializers);
        __esDecorate(null, null, _ticketTags_decorators, { kind: "field", name: "ticketTags", static: false, private: false, access: { has: function (obj) { return "ticketTags" in obj; }, get: function (obj) { return obj.ticketTags; }, set: function (obj, value) { obj.ticketTags = value; } }, metadata: _metadata }, _ticketTags_initializers, _ticketTags_extraInitializers);
        __esDecorate(null, null, _tags_decorators, { kind: "field", name: "tags", static: false, private: false, access: { has: function (obj) { return "tags" in obj; }, get: function (obj) { return obj.tags; }, set: function (obj, value) { obj.tags = value; } }, metadata: _metadata }, _tags_initializers, _tags_extraInitializers);
        __esDecorate(null, null, _companyId_decorators, { kind: "field", name: "companyId", static: false, private: false, access: { has: function (obj) { return "companyId" in obj; }, get: function (obj) { return obj.companyId; }, set: function (obj, value) { obj.companyId = value; } }, metadata: _metadata }, _companyId_initializers, _companyId_extraInitializers);
        __esDecorate(null, null, _company_decorators, { kind: "field", name: "company", static: false, private: false, access: { has: function (obj) { return "company" in obj; }, get: function (obj) { return obj.company; }, set: function (obj, value) { obj.company = value; } }, metadata: _metadata }, _company_initializers, _company_extraInitializers);
        __esDecorate(null, null, _uuid_decorators, { kind: "field", name: "uuid", static: false, private: false, access: { has: function (obj) { return "uuid" in obj; }, get: function (obj) { return obj.uuid; }, set: function (obj, value) { obj.uuid = value; } }, metadata: _metadata }, _uuid_initializers, _uuid_extraInitializers);
        __esDecorate(null, null, _useIntegration_decorators, { kind: "field", name: "useIntegration", static: false, private: false, access: { has: function (obj) { return "useIntegration" in obj; }, get: function (obj) { return obj.useIntegration; }, set: function (obj, value) { obj.useIntegration = value; } }, metadata: _metadata }, _useIntegration_initializers, _useIntegration_extraInitializers);
        __esDecorate(null, null, _integrationId_decorators, { kind: "field", name: "integrationId", static: false, private: false, access: { has: function (obj) { return "integrationId" in obj; }, get: function (obj) { return obj.integrationId; }, set: function (obj, value) { obj.integrationId = value; } }, metadata: _metadata }, _integrationId_initializers, _integrationId_extraInitializers);
        __esDecorate(null, null, _queueIntegration_decorators, { kind: "field", name: "queueIntegration", static: false, private: false, access: { has: function (obj) { return "queueIntegration" in obj; }, get: function (obj) { return obj.queueIntegration; }, set: function (obj, value) { obj.queueIntegration = value; } }, metadata: _metadata }, _queueIntegration_initializers, _queueIntegration_extraInitializers);
        __esDecorate(null, null, _typebotSessionId_decorators, { kind: "field", name: "typebotSessionId", static: false, private: false, access: { has: function (obj) { return "typebotSessionId" in obj; }, get: function (obj) { return obj.typebotSessionId; }, set: function (obj, value) { obj.typebotSessionId = value; } }, metadata: _metadata }, _typebotSessionId_initializers, _typebotSessionId_extraInitializers);
        __esDecorate(null, null, _typebotStatus_decorators, { kind: "field", name: "typebotStatus", static: false, private: false, access: { has: function (obj) { return "typebotStatus" in obj; }, get: function (obj) { return obj.typebotStatus; }, set: function (obj, value) { obj.typebotStatus = value; } }, metadata: _metadata }, _typebotStatus_initializers, _typebotStatus_extraInitializers);
        __esDecorate(null, null, _promptId_decorators, { kind: "field", name: "promptId", static: false, private: false, access: { has: function (obj) { return "promptId" in obj; }, get: function (obj) { return obj.promptId; }, set: function (obj, value) { obj.promptId = value; } }, metadata: _metadata }, _promptId_initializers, _promptId_extraInitializers);
        __esDecorate(null, null, _prompt_decorators, { kind: "field", name: "prompt", static: false, private: false, access: { has: function (obj) { return "prompt" in obj; }, get: function (obj) { return obj.prompt; }, set: function (obj, value) { obj.prompt = value; } }, metadata: _metadata }, _prompt_initializers, _prompt_extraInitializers);
        __esDecorate(null, null, _fromMe_decorators, { kind: "field", name: "fromMe", static: false, private: false, access: { has: function (obj) { return "fromMe" in obj; }, get: function (obj) { return obj.fromMe; }, set: function (obj, value) { obj.fromMe = value; } }, metadata: _metadata }, _fromMe_initializers, _fromMe_extraInitializers);
        __esDecorate(null, null, _amountUsedBotQueues_decorators, { kind: "field", name: "amountUsedBotQueues", static: false, private: false, access: { has: function (obj) { return "amountUsedBotQueues" in obj; }, get: function (obj) { return obj.amountUsedBotQueues; }, set: function (obj, value) { obj.amountUsedBotQueues = value; } }, metadata: _metadata }, _amountUsedBotQueues_initializers, _amountUsedBotQueues_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Ticket = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _staticExtraInitializers);
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Ticket = _classThis;
}();
exports.default = Ticket;
