"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
var sequelize_typescript_1 = require("sequelize-typescript");
var Queue_1 = require("./Queue");
var Ticket_1 = require("./Ticket");
var WhatsappQueue_1 = require("./WhatsappQueue");
var Company_1 = require("./Company");
var Prompt_1 = require("./Prompt");
var QueueIntegrations_1 = require("./QueueIntegrations");
var Whatsapp = function () {
    var _classDecorators = [sequelize_typescript_1.Table];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _classSuper = sequelize_typescript_1.Model;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _name_decorators;
    var _name_initializers = [];
    var _name_extraInitializers = [];
    var _session_decorators;
    var _session_initializers = [];
    var _session_extraInitializers = [];
    var _qrcode_decorators;
    var _qrcode_initializers = [];
    var _qrcode_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _battery_decorators;
    var _battery_initializers = [];
    var _battery_extraInitializers = [];
    var _plugged_decorators;
    var _plugged_initializers = [];
    var _plugged_extraInitializers = [];
    var _retries_decorators;
    var _retries_initializers = [];
    var _retries_extraInitializers = [];
    var _greetingMessage_decorators;
    var _greetingMessage_initializers = [];
    var _greetingMessage_extraInitializers = [];
    var _farewellMessage_decorators;
    var _farewellMessage_initializers = [];
    var _farewellMessage_extraInitializers = [];
    var _complationMessage_decorators;
    var _complationMessage_initializers = [];
    var _complationMessage_extraInitializers = [];
    var _outOfHoursMessage_decorators;
    var _outOfHoursMessage_initializers = [];
    var _outOfHoursMessage_extraInitializers = [];
    var _ratingMessage_decorators;
    var _ratingMessage_initializers = [];
    var _ratingMessage_extraInitializers = [];
    var _provider_decorators;
    var _provider_initializers = [];
    var _provider_extraInitializers = [];
    var _isDefault_decorators;
    var _isDefault_initializers = [];
    var _isDefault_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var _tickets_decorators;
    var _tickets_initializers = [];
    var _tickets_extraInitializers = [];
    var _queues_decorators;
    var _queues_initializers = [];
    var _queues_extraInitializers = [];
    var _whatsappQueues_decorators;
    var _whatsappQueues_initializers = [];
    var _whatsappQueues_extraInitializers = [];
    var _companyId_decorators;
    var _companyId_initializers = [];
    var _companyId_extraInitializers = [];
    var _company_decorators;
    var _company_initializers = [];
    var _company_extraInitializers = [];
    var _token_decorators;
    var _token_initializers = [];
    var _token_extraInitializers = [];
    var _transferQueueId_decorators;
    var _transferQueueId_initializers = [];
    var _transferQueueId_extraInitializers = [];
    var _timeToTransfer_decorators;
    var _timeToTransfer_initializers = [];
    var _timeToTransfer_extraInitializers = [];
    var _promptId_decorators;
    var _promptId_initializers = [];
    var _promptId_extraInitializers = [];
    var _prompt_decorators;
    var _prompt_initializers = [];
    var _prompt_extraInitializers = [];
    var _integrationId_decorators;
    var _integrationId_initializers = [];
    var _integrationId_extraInitializers = [];
    var _queueIntegrations_decorators;
    var _queueIntegrations_initializers = [];
    var _queueIntegrations_extraInitializers = [];
    var _maxUseBotQueues_decorators;
    var _maxUseBotQueues_initializers = [];
    var _maxUseBotQueues_extraInitializers = [];
    var _timeUseBotQueues_decorators;
    var _timeUseBotQueues_initializers = [];
    var _timeUseBotQueues_extraInitializers = [];
    var _expiresTicket_decorators;
    var _expiresTicket_initializers = [];
    var _expiresTicket_extraInitializers = [];
    var _expiresInactiveMessage_decorators;
    var _expiresInactiveMessage_initializers = [];
    var _expiresInactiveMessage_extraInitializers = [];
    var Whatsapp = _classThis = /** @class */ (function (_super) {
        __extends(Whatsapp_1, _super);
        function Whatsapp_1() {
            var _this = _super !== null && _super.apply(this, arguments) || this;
            _this.id = __runInitializers(_this, _id_initializers, void 0);
            _this.name = (__runInitializers(_this, _id_extraInitializers), __runInitializers(_this, _name_initializers, void 0));
            _this.session = (__runInitializers(_this, _name_extraInitializers), __runInitializers(_this, _session_initializers, void 0));
            _this.qrcode = (__runInitializers(_this, _session_extraInitializers), __runInitializers(_this, _qrcode_initializers, void 0));
            _this.status = (__runInitializers(_this, _qrcode_extraInitializers), __runInitializers(_this, _status_initializers, void 0));
            _this.battery = (__runInitializers(_this, _status_extraInitializers), __runInitializers(_this, _battery_initializers, void 0));
            _this.plugged = (__runInitializers(_this, _battery_extraInitializers), __runInitializers(_this, _plugged_initializers, void 0));
            _this.retries = (__runInitializers(_this, _plugged_extraInitializers), __runInitializers(_this, _retries_initializers, void 0));
            _this.greetingMessage = (__runInitializers(_this, _retries_extraInitializers), __runInitializers(_this, _greetingMessage_initializers, void 0));
            _this.farewellMessage = (__runInitializers(_this, _greetingMessage_extraInitializers), __runInitializers(_this, _farewellMessage_initializers, void 0));
            _this.complationMessage = (__runInitializers(_this, _farewellMessage_extraInitializers), __runInitializers(_this, _complationMessage_initializers, void 0));
            _this.outOfHoursMessage = (__runInitializers(_this, _complationMessage_extraInitializers), __runInitializers(_this, _outOfHoursMessage_initializers, void 0));
            _this.ratingMessage = (__runInitializers(_this, _outOfHoursMessage_extraInitializers), __runInitializers(_this, _ratingMessage_initializers, void 0));
            _this.provider = (__runInitializers(_this, _ratingMessage_extraInitializers), __runInitializers(_this, _provider_initializers, void 0));
            _this.isDefault = (__runInitializers(_this, _provider_extraInitializers), __runInitializers(_this, _isDefault_initializers, void 0));
            _this.createdAt = (__runInitializers(_this, _isDefault_extraInitializers), __runInitializers(_this, _createdAt_initializers, void 0));
            _this.updatedAt = (__runInitializers(_this, _createdAt_extraInitializers), __runInitializers(_this, _updatedAt_initializers, void 0));
            _this.tickets = (__runInitializers(_this, _updatedAt_extraInitializers), __runInitializers(_this, _tickets_initializers, void 0));
            _this.queues = (__runInitializers(_this, _tickets_extraInitializers), __runInitializers(_this, _queues_initializers, void 0));
            _this.whatsappQueues = (__runInitializers(_this, _queues_extraInitializers), __runInitializers(_this, _whatsappQueues_initializers, void 0));
            _this.companyId = (__runInitializers(_this, _whatsappQueues_extraInitializers), __runInitializers(_this, _companyId_initializers, void 0));
            _this.company = (__runInitializers(_this, _companyId_extraInitializers), __runInitializers(_this, _company_initializers, void 0));
            _this.token = (__runInitializers(_this, _company_extraInitializers), __runInitializers(_this, _token_initializers, void 0));
            //@Default(0)
            //@Column
            //timeSendQueue: number;
            //@Column
            //sendIdQueue: number;
            _this.transferQueueId = (__runInitializers(_this, _token_extraInitializers), __runInitializers(_this, _transferQueueId_initializers, void 0));
            _this.timeToTransfer = (__runInitializers(_this, _transferQueueId_extraInitializers), __runInitializers(_this, _timeToTransfer_initializers, void 0));
            _this.promptId = (__runInitializers(_this, _timeToTransfer_extraInitializers), __runInitializers(_this, _promptId_initializers, void 0));
            _this.prompt = (__runInitializers(_this, _promptId_extraInitializers), __runInitializers(_this, _prompt_initializers, void 0));
            _this.integrationId = (__runInitializers(_this, _prompt_extraInitializers), __runInitializers(_this, _integrationId_initializers, void 0));
            _this.queueIntegrations = (__runInitializers(_this, _integrationId_extraInitializers), __runInitializers(_this, _queueIntegrations_initializers, void 0));
            _this.maxUseBotQueues = (__runInitializers(_this, _queueIntegrations_extraInitializers), __runInitializers(_this, _maxUseBotQueues_initializers, void 0));
            _this.timeUseBotQueues = (__runInitializers(_this, _maxUseBotQueues_extraInitializers), __runInitializers(_this, _timeUseBotQueues_initializers, void 0));
            _this.expiresTicket = (__runInitializers(_this, _timeUseBotQueues_extraInitializers), __runInitializers(_this, _expiresTicket_initializers, void 0));
            _this.expiresInactiveMessage = (__runInitializers(_this, _expiresTicket_extraInitializers), __runInitializers(_this, _expiresInactiveMessage_initializers, void 0));
            __runInitializers(_this, _expiresInactiveMessage_extraInitializers);
            return _this;
        }
        return Whatsapp_1;
    }(_classSuper));
    __setFunctionName(_classThis, "Whatsapp");
    (function () {
        var _a;
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create((_a = _classSuper[Symbol.metadata]) !== null && _a !== void 0 ? _a : null) : void 0;
        _id_decorators = [sequelize_typescript_1.PrimaryKey, sequelize_typescript_1.AutoIncrement, sequelize_typescript_1.Column];
        _name_decorators = [sequelize_typescript_1.AllowNull, sequelize_typescript_1.Unique, (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.TEXT)];
        _session_decorators = [(0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.TEXT)];
        _qrcode_decorators = [(0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.TEXT)];
        _status_decorators = [sequelize_typescript_1.Column];
        _battery_decorators = [sequelize_typescript_1.Column];
        _plugged_decorators = [sequelize_typescript_1.Column];
        _retries_decorators = [sequelize_typescript_1.Column];
        _greetingMessage_decorators = [(0, sequelize_typescript_1.Default)(""), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.TEXT)];
        _farewellMessage_decorators = [(0, sequelize_typescript_1.Default)(""), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.TEXT)];
        _complationMessage_decorators = [(0, sequelize_typescript_1.Default)(""), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.TEXT)];
        _outOfHoursMessage_decorators = [(0, sequelize_typescript_1.Default)(""), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.TEXT)];
        _ratingMessage_decorators = [(0, sequelize_typescript_1.Default)(""), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.TEXT)];
        _provider_decorators = [(0, sequelize_typescript_1.Column)({ defaultValue: "stable" })];
        _isDefault_decorators = [(0, sequelize_typescript_1.Default)(false), sequelize_typescript_1.AllowNull, sequelize_typescript_1.Column];
        _createdAt_decorators = [sequelize_typescript_1.CreatedAt];
        _updatedAt_decorators = [sequelize_typescript_1.UpdatedAt];
        _tickets_decorators = [(0, sequelize_typescript_1.HasMany)(function () { return Ticket_1.default; })];
        _queues_decorators = [(0, sequelize_typescript_1.BelongsToMany)(function () { return Queue_1.default; }, function () { return WhatsappQueue_1.default; })];
        _whatsappQueues_decorators = [(0, sequelize_typescript_1.HasMany)(function () { return WhatsappQueue_1.default; })];
        _companyId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return Company_1.default; }), sequelize_typescript_1.Column];
        _company_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return Company_1.default; })];
        _token_decorators = [sequelize_typescript_1.Column];
        _transferQueueId_decorators = [sequelize_typescript_1.Column];
        _timeToTransfer_decorators = [sequelize_typescript_1.Column];
        _promptId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return Prompt_1.default; }), sequelize_typescript_1.Column];
        _prompt_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return Prompt_1.default; })];
        _integrationId_decorators = [(0, sequelize_typescript_1.ForeignKey)(function () { return QueueIntegrations_1.default; }), sequelize_typescript_1.Column];
        _queueIntegrations_decorators = [(0, sequelize_typescript_1.BelongsTo)(function () { return QueueIntegrations_1.default; })];
        _maxUseBotQueues_decorators = [sequelize_typescript_1.Column];
        _timeUseBotQueues_decorators = [sequelize_typescript_1.Column];
        _expiresTicket_decorators = [sequelize_typescript_1.Column];
        _expiresInactiveMessage_decorators = [sequelize_typescript_1.Column];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _name_decorators, { kind: "field", name: "name", static: false, private: false, access: { has: function (obj) { return "name" in obj; }, get: function (obj) { return obj.name; }, set: function (obj, value) { obj.name = value; } }, metadata: _metadata }, _name_initializers, _name_extraInitializers);
        __esDecorate(null, null, _session_decorators, { kind: "field", name: "session", static: false, private: false, access: { has: function (obj) { return "session" in obj; }, get: function (obj) { return obj.session; }, set: function (obj, value) { obj.session = value; } }, metadata: _metadata }, _session_initializers, _session_extraInitializers);
        __esDecorate(null, null, _qrcode_decorators, { kind: "field", name: "qrcode", static: false, private: false, access: { has: function (obj) { return "qrcode" in obj; }, get: function (obj) { return obj.qrcode; }, set: function (obj, value) { obj.qrcode = value; } }, metadata: _metadata }, _qrcode_initializers, _qrcode_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _battery_decorators, { kind: "field", name: "battery", static: false, private: false, access: { has: function (obj) { return "battery" in obj; }, get: function (obj) { return obj.battery; }, set: function (obj, value) { obj.battery = value; } }, metadata: _metadata }, _battery_initializers, _battery_extraInitializers);
        __esDecorate(null, null, _plugged_decorators, { kind: "field", name: "plugged", static: false, private: false, access: { has: function (obj) { return "plugged" in obj; }, get: function (obj) { return obj.plugged; }, set: function (obj, value) { obj.plugged = value; } }, metadata: _metadata }, _plugged_initializers, _plugged_extraInitializers);
        __esDecorate(null, null, _retries_decorators, { kind: "field", name: "retries", static: false, private: false, access: { has: function (obj) { return "retries" in obj; }, get: function (obj) { return obj.retries; }, set: function (obj, value) { obj.retries = value; } }, metadata: _metadata }, _retries_initializers, _retries_extraInitializers);
        __esDecorate(null, null, _greetingMessage_decorators, { kind: "field", name: "greetingMessage", static: false, private: false, access: { has: function (obj) { return "greetingMessage" in obj; }, get: function (obj) { return obj.greetingMessage; }, set: function (obj, value) { obj.greetingMessage = value; } }, metadata: _metadata }, _greetingMessage_initializers, _greetingMessage_extraInitializers);
        __esDecorate(null, null, _farewellMessage_decorators, { kind: "field", name: "farewellMessage", static: false, private: false, access: { has: function (obj) { return "farewellMessage" in obj; }, get: function (obj) { return obj.farewellMessage; }, set: function (obj, value) { obj.farewellMessage = value; } }, metadata: _metadata }, _farewellMessage_initializers, _farewellMessage_extraInitializers);
        __esDecorate(null, null, _complationMessage_decorators, { kind: "field", name: "complationMessage", static: false, private: false, access: { has: function (obj) { return "complationMessage" in obj; }, get: function (obj) { return obj.complationMessage; }, set: function (obj, value) { obj.complationMessage = value; } }, metadata: _metadata }, _complationMessage_initializers, _complationMessage_extraInitializers);
        __esDecorate(null, null, _outOfHoursMessage_decorators, { kind: "field", name: "outOfHoursMessage", static: false, private: false, access: { has: function (obj) { return "outOfHoursMessage" in obj; }, get: function (obj) { return obj.outOfHoursMessage; }, set: function (obj, value) { obj.outOfHoursMessage = value; } }, metadata: _metadata }, _outOfHoursMessage_initializers, _outOfHoursMessage_extraInitializers);
        __esDecorate(null, null, _ratingMessage_decorators, { kind: "field", name: "ratingMessage", static: false, private: false, access: { has: function (obj) { return "ratingMessage" in obj; }, get: function (obj) { return obj.ratingMessage; }, set: function (obj, value) { obj.ratingMessage = value; } }, metadata: _metadata }, _ratingMessage_initializers, _ratingMessage_extraInitializers);
        __esDecorate(null, null, _provider_decorators, { kind: "field", name: "provider", static: false, private: false, access: { has: function (obj) { return "provider" in obj; }, get: function (obj) { return obj.provider; }, set: function (obj, value) { obj.provider = value; } }, metadata: _metadata }, _provider_initializers, _provider_extraInitializers);
        __esDecorate(null, null, _isDefault_decorators, { kind: "field", name: "isDefault", static: false, private: false, access: { has: function (obj) { return "isDefault" in obj; }, get: function (obj) { return obj.isDefault; }, set: function (obj, value) { obj.isDefault = value; } }, metadata: _metadata }, _isDefault_initializers, _isDefault_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, null, _tickets_decorators, { kind: "field", name: "tickets", static: false, private: false, access: { has: function (obj) { return "tickets" in obj; }, get: function (obj) { return obj.tickets; }, set: function (obj, value) { obj.tickets = value; } }, metadata: _metadata }, _tickets_initializers, _tickets_extraInitializers);
        __esDecorate(null, null, _queues_decorators, { kind: "field", name: "queues", static: false, private: false, access: { has: function (obj) { return "queues" in obj; }, get: function (obj) { return obj.queues; }, set: function (obj, value) { obj.queues = value; } }, metadata: _metadata }, _queues_initializers, _queues_extraInitializers);
        __esDecorate(null, null, _whatsappQueues_decorators, { kind: "field", name: "whatsappQueues", static: false, private: false, access: { has: function (obj) { return "whatsappQueues" in obj; }, get: function (obj) { return obj.whatsappQueues; }, set: function (obj, value) { obj.whatsappQueues = value; } }, metadata: _metadata }, _whatsappQueues_initializers, _whatsappQueues_extraInitializers);
        __esDecorate(null, null, _companyId_decorators, { kind: "field", name: "companyId", static: false, private: false, access: { has: function (obj) { return "companyId" in obj; }, get: function (obj) { return obj.companyId; }, set: function (obj, value) { obj.companyId = value; } }, metadata: _metadata }, _companyId_initializers, _companyId_extraInitializers);
        __esDecorate(null, null, _company_decorators, { kind: "field", name: "company", static: false, private: false, access: { has: function (obj) { return "company" in obj; }, get: function (obj) { return obj.company; }, set: function (obj, value) { obj.company = value; } }, metadata: _metadata }, _company_initializers, _company_extraInitializers);
        __esDecorate(null, null, _token_decorators, { kind: "field", name: "token", static: false, private: false, access: { has: function (obj) { return "token" in obj; }, get: function (obj) { return obj.token; }, set: function (obj, value) { obj.token = value; } }, metadata: _metadata }, _token_initializers, _token_extraInitializers);
        __esDecorate(null, null, _transferQueueId_decorators, { kind: "field", name: "transferQueueId", static: false, private: false, access: { has: function (obj) { return "transferQueueId" in obj; }, get: function (obj) { return obj.transferQueueId; }, set: function (obj, value) { obj.transferQueueId = value; } }, metadata: _metadata }, _transferQueueId_initializers, _transferQueueId_extraInitializers);
        __esDecorate(null, null, _timeToTransfer_decorators, { kind: "field", name: "timeToTransfer", static: false, private: false, access: { has: function (obj) { return "timeToTransfer" in obj; }, get: function (obj) { return obj.timeToTransfer; }, set: function (obj, value) { obj.timeToTransfer = value; } }, metadata: _metadata }, _timeToTransfer_initializers, _timeToTransfer_extraInitializers);
        __esDecorate(null, null, _promptId_decorators, { kind: "field", name: "promptId", static: false, private: false, access: { has: function (obj) { return "promptId" in obj; }, get: function (obj) { return obj.promptId; }, set: function (obj, value) { obj.promptId = value; } }, metadata: _metadata }, _promptId_initializers, _promptId_extraInitializers);
        __esDecorate(null, null, _prompt_decorators, { kind: "field", name: "prompt", static: false, private: false, access: { has: function (obj) { return "prompt" in obj; }, get: function (obj) { return obj.prompt; }, set: function (obj, value) { obj.prompt = value; } }, metadata: _metadata }, _prompt_initializers, _prompt_extraInitializers);
        __esDecorate(null, null, _integrationId_decorators, { kind: "field", name: "integrationId", static: false, private: false, access: { has: function (obj) { return "integrationId" in obj; }, get: function (obj) { return obj.integrationId; }, set: function (obj, value) { obj.integrationId = value; } }, metadata: _metadata }, _integrationId_initializers, _integrationId_extraInitializers);
        __esDecorate(null, null, _queueIntegrations_decorators, { kind: "field", name: "queueIntegrations", static: false, private: false, access: { has: function (obj) { return "queueIntegrations" in obj; }, get: function (obj) { return obj.queueIntegrations; }, set: function (obj, value) { obj.queueIntegrations = value; } }, metadata: _metadata }, _queueIntegrations_initializers, _queueIntegrations_extraInitializers);
        __esDecorate(null, null, _maxUseBotQueues_decorators, { kind: "field", name: "maxUseBotQueues", static: false, private: false, access: { has: function (obj) { return "maxUseBotQueues" in obj; }, get: function (obj) { return obj.maxUseBotQueues; }, set: function (obj, value) { obj.maxUseBotQueues = value; } }, metadata: _metadata }, _maxUseBotQueues_initializers, _maxUseBotQueues_extraInitializers);
        __esDecorate(null, null, _timeUseBotQueues_decorators, { kind: "field", name: "timeUseBotQueues", static: false, private: false, access: { has: function (obj) { return "timeUseBotQueues" in obj; }, get: function (obj) { return obj.timeUseBotQueues; }, set: function (obj, value) { obj.timeUseBotQueues = value; } }, metadata: _metadata }, _timeUseBotQueues_initializers, _timeUseBotQueues_extraInitializers);
        __esDecorate(null, null, _expiresTicket_decorators, { kind: "field", name: "expiresTicket", static: false, private: false, access: { has: function (obj) { return "expiresTicket" in obj; }, get: function (obj) { return obj.expiresTicket; }, set: function (obj, value) { obj.expiresTicket = value; } }, metadata: _metadata }, _expiresTicket_initializers, _expiresTicket_extraInitializers);
        __esDecorate(null, null, _expiresInactiveMessage_decorators, { kind: "field", name: "expiresInactiveMessage", static: false, private: false, access: { has: function (obj) { return "expiresInactiveMessage" in obj; }, get: function (obj) { return obj.expiresInactiveMessage; }, set: function (obj, value) { obj.expiresInactiveMessage = value; } }, metadata: _metadata }, _expiresInactiveMessage_initializers, _expiresInactiveMessage_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Whatsapp = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Whatsapp = _classThis;
}();
exports.default = Whatsapp;
